### ISSUE TITLE
offset of glm.fit (not a real issue, just some math)

### ISSUE THREAD

**Issue by liu-xingliang** [saketkc/scRNA_NB_comparison#1]
Dear @saketkc ,

I came across the supplemental method part of the paper talking about"Goodness of Fit test using a Poisson GLM" and noted that a offset term was used when modeling UMI count per gene:

```r
glm.fit(gene_umi∼1, offset=log(total_umi),family=Poisson(link="log")
```

After read a few threads [here](https://stats.stackexchange.com/questions/175349/in-a-poisson-model-what-is-the-difference-between-using-time-as-a-covariate-or) and [here](https://stats.stackexchange.com/questions/11182/when-to-use-an-offset-in-a-poisson-regression). I want to confirm my understanding of offset usage in this context.

I think the model you tried to fit is:

```
log(gene_umi/total_umi) ~ 1
```

`total_umi` here is used as estimation of total transcripts of a cell (population, vs sample) and 50 UMIs in TP53 of total 1,000 transcripts is different with 50 UMIs of TP53 of total 10,000 transcripts of given cell.

Would like to know more about the rationale, thank you for your help!

bless~

**Comment by saketkc** [comment]
Thanks for the question @liuxl18-hku. Right, the idea here is to model the "rate" of transcription. For a given total UMI, each gene gets a certain proportion of UMIs assigned to it based on its "rate" of transcription such that 

observed gene UMI = Poisson (rate * total cell UMI) 

Your example of TP53 also highlights this point: here the "rate" of TP53 is different in the two cells.

**Comment by liu-xingliang** [comment]
Thank you, I know more now. The insights of the paper are very interesting~
